//HintName: EndpointExtensions.g.cs
// <auto-generated>
//   Generated by the IeuanWalker.MinimalApi.Endpoints
//   https://github.com/IeuanWalker/IeuanWalker.MinimalApi.Endpoints
// </auto-generated>

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System.Threading;
using IeuanWalker.MinimalApi.Endpoints.Filters;
using FluentValidation;

namespace TestAssembly;

public static class EndpointExtensions
{
	public static IHostApplicationBuilder AddEndpointsFromTestAssembly(this IHostApplicationBuilder builder)
	{
		builder.Services.AddScoped<global::TestNamespace.DisabledValidationEndpoint>();

		// Validators not directly related to an endpoints request model
		builder.Services.AddSingleton<IValidator<global::TestNamespace.CreateRequest>, global::TestNamespace.CreateRequestValidator>();

		return builder;
	}

	public static WebApplication MapEndpointsFromTestAssembly(this WebApplication app)
	{
		// POST: /api/novalid
		RouteHandlerBuilder post_Novalid_0 = app
			.MapPost("/api/novalid", async (
				global::TestNamespace.CreateRequest request,
				[FromServices] global::TestNamespace.DisabledValidationEndpoint endpoint,
				CancellationToken ct) => await endpoint.Handle(request, ct))
			.WithTags("Novalid")
			.WithName("post_Novalid_0");

		global::TestNamespace.DisabledValidationEndpoint.Configure(post_Novalid_0);

		return app;
	}
}
