//HintName: EndpointExtensions.g.cs
// <auto-generated>
//   Generated by the IeuanWalker.MinimalApi.Endpoints
//   https://github.com/IeuanWalker/IeuanWalker.MinimalApi.Endpoints
// </auto-generated>

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System.Threading;

namespace TestAssembly;

public static class EndpointExtensions
{
	public static IHostApplicationBuilder AddEndpoints(this IHostApplicationBuilder builder) => builder.AddEndpointsFromTestAssembly();
	public static IHostApplicationBuilder AddEndpointsFromTestAssembly(this IHostApplicationBuilder builder)
	{
		builder.Services.AddScoped<global::TestNamespace.CreateUserEndpoint>();

		return builder;
	}

	public static WebApplication MapEndpoints(this WebApplication app) => app.MapEndpointsFromTestAssembly();
	public static WebApplication MapEndpointsFromTestAssembly(this WebApplication app)
	{
		// POST: /api/users
		RouteHandlerBuilder post_Users_0 = app
			.MapPost("/api/users", async (
				[FromBody] global::TestNamespace.CreateUserRequest request,
				[FromServices] global::TestNamespace.CreateUserEndpoint endpoint,
				CancellationToken ct) => await endpoint.Handle(request, ct))
			.WithTags("Users")
			.WithName("post_Users_0");

		global::TestNamespace.CreateUserEndpoint.Configure(post_Users_0);

		return app;
	}
}
