//HintName: EndpointExtensions.g.cs
// <auto-generated>
//   Generated by the IeuanWalker.MinimalApi.Endpoints
//   https://github.com/IeuanWalker/IeuanWalker.MinimalApi.Endpoints
// </auto-generated>

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System.Threading;

namespace TestAssembly;

#pragma warning disable ASP0018 // Disable specific ASP.NET analyzer that warns about unused route parameters in generated handlers

public static class EndpointExtensions
{
	public static IHostApplicationBuilder AddEndpoints(this IHostApplicationBuilder builder) => builder.AddEndpointsFromTestAssembly();
	public static IHostApplicationBuilder AddEndpointsFromTestAssembly(this IHostApplicationBuilder builder)
	{
		builder.Services.AddScoped<global::TestNamespace.GetUserEndpoint>();

		return builder;
	}

	public static WebApplication MapEndpoints(this WebApplication app) => app.MapEndpointsFromTestAssembly();
	public static WebApplication MapEndpointsFromTestAssembly(this WebApplication app)
	{
		// GET: /api/users/current
		RouteHandlerBuilder get_UsersCurrent_0 = app
			.MapGet("/api/users/current", async (
				[FromHeader] global::TestNamespace.GetUserRequest request,
				[FromServices] global::TestNamespace.GetUserEndpoint endpoint,
				CancellationToken ct) => await endpoint.Handle(request, ct))
			.WithTags("Users")
			.WithName("get_UsersCurrent_0");

		global::TestNamespace.GetUserEndpoint.Configure(get_UsersCurrent_0);

		return app;
	}
}

#pragma warning restore ASP0018
