//HintName: EndpointExtensions.g.cs
// <auto-generated>
//   Generated by the IeuanWalker.MinimalApi.Endpoints
//   https://github.com/IeuanWalker/IeuanWalker.MinimalApi.Endpoints
// </auto-generated>

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace TestAssembly;

public static class EndpointExtensions
{
	public static IHostApplicationBuilder AddEndpointsFromTestAssembly(this IHostApplicationBuilder builder)
	{
		builder.Services.AddScoped<global::TestNamespace.SearchUsersEndpoint>();

		return builder;
	}

	public static WebApplication MapEndpointsFromTestAssembly(this WebApplication app)
	{
		// GET: /api/users/search
		RouteHandlerBuilder get_UsersSearch_0 = app
			.MapGet("/api/users/search", async (
				[AsParameters] global::TestNamespace.SearchUsersRequest request,
				[FromServices] global::TestNamespace.SearchUsersEndpoint endpoint,
				CancellationToken ct) => await endpoint.Handle(request, ct))
			.WithTags("Users")
			.WithName("get_UsersSearch_0");

		global::TestNamespace.SearchUsersEndpoint.Configure(get_UsersSearch_0);

		return app;
	}
}
