//HintName: EndpointExtensions.g.cs
// <auto-generated>
//   Generated by the IeuanWalker.MinimalApi.Endpoints
//   https://github.com/IeuanWalker/IeuanWalker.MinimalApi.Endpoints
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using IeuanWalker.MinimalApi.Endpoints.Filters;
using FluentValidation;

namespace TestAssembly;

public static class EndpointExtensions
{
    public static IHostApplicationBuilder AddEndpointsFromTestAssembly(this IHostApplicationBuilder builder)
    {
        builder.Services.AddSingleton<IValidator<global::TestNamespace.CreateUserRequest>, global::TestNamespace.CreateUserRequestValidator>();
        builder.Services.AddScoped<global::TestNamespace.CreateUserEndpoint>();
        
        return builder;
    }
    
    public static WebApplication MapEndpointsFromTestAssembly(this WebApplication app)
    {
        // **************************************
        // GROUP: TestNamespace.UserEndpointGroup
        // 1 endpoints
        // **************************************
        RouteGroupBuilder group_userEndpointGroup_0 = TestNamespace.UserEndpointGroup.Configure(app);
        
        // POST: /api/v1/users/
        RouteHandlerBuilder post_Users_0 = group_userEndpointGroup_0
            .MapPost("/", async (
                [FromBody] global::TestNamespace.CreateUserRequest request,
                [FromServices] global::TestNamespace.CreateUserEndpoint endpoint,
                CancellationToken ct) => await endpoint.Handle(request, ct))
            .DisableValidation()
            .AddEndpointFilter<FluentValidationFilter<global::TestNamespace.CreateUserRequest>>()
            .ProducesValidationProblem();
        
        global::TestNamespace.CreateUserEndpoint.Configure(post_Users_0);
        
        return app;
    }
}
