//HintName: EndpointExtensions.g.cs
// <auto-generated>
//   Generated by the IeuanWalker.MinimalApi.Endpoints
//   https://github.com/IeuanWalker/IeuanWalker.MinimalApi.Endpoints
// </auto-generated>

using Microsoft.AspNetCore.Mvc;

namespace TestAssembly;

public static class EndpointExtensions
{
    public static IHostApplicationBuilder AddEndpointsFromTestAssembly(this IHostApplicationBuilder builder)
    {
        builder.Services.AddScoped<global::TestNamespace.UploadFileEndpoint>();
        
        return builder;
    }
    
    public static WebApplication MapEndpointsFromTestAssembly(this WebApplication app)
    {
        // POST: /api/files
        RouteHandlerBuilder post_Files_0 = app
            .MapPost("/api/files", async (
                [FromForm] global::TestNamespace.UploadFileRequest request,
                [FromServices] global::TestNamespace.UploadFileEndpoint endpoint,
                CancellationToken ct) => await endpoint.Handle(request, ct))
            .WithTags("Files")
            .WithName("post_Files_0");
        
        global::TestNamespace.UploadFileEndpoint.Configure(post_Files_0);
        
        return app;
    }
}
