//HintName: EndpointExtensions.g.cs
// <auto-generated>
//   Generated by the IeuanWalker.MinimalApi.Endpoints
//   https://github.com/IeuanWalker/IeuanWalker.MinimalApi.Endpoints
// </auto-generated>

using Microsoft.AspNetCore.Mvc;

namespace TestAssembly;

public static class EndpointExtensions
{
    public static IHostApplicationBuilder AddEndpointsFromTestAssembly(this IHostApplicationBuilder builder)
    {
        builder.Services.AddScoped<global::TestNamespace.HealthCheckEndpoint>();
        
        return builder;
    }
    
    public static WebApplication MapEndpointsFromTestAssembly(this WebApplication app)
    {
        // GET: /health
        RouteHandlerBuilder get_Health_0 = app
            .MapGet("/health", async (
                [FromServices] global::TestNamespace.HealthCheckEndpoint endpoint,
                CancellationToken ct) => await endpoint.Handle(ct))
            .WithTags("Health")
            .WithName("get_Health_0");
        
        global::TestNamespace.HealthCheckEndpoint.Configure(get_Health_0);
        
        return app;
    }
}
